"""Initial RecoverAI schema

Revision ID: f432cf614865
Revises: 
Create Date: 2026-08-22 21:27:08.313344

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f432cf614865'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('entity_name', sa.String(length=64), nullable=False),
    sa.Column('entity_id', sa.String(length=64), nullable=False),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('actor', sa.String(length=64), nullable=False),
    sa.Column('state_before', sa.JSON(), nullable=True),
    sa.Column('state_after', sa.JSON(), nullable=False),
    sa.Column('prev_hash', sa.String(length=64), nullable=True),
    sa.Column('sha256_hash', sa.String(length=64), nullable=False),
    sa.Column('timestamp_iso', sa.String(length=36), nullable=False),
    sa.Column('notes', sa.String(length=512), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_audit_entity_created', 'audit_logs', ['entity_name', 'entity_id', 'created_at'], unique=False)
    op.create_index('ix_audit_event_created', 'audit_logs', ['event_type', 'created_at'], unique=False)
    op.create_index(op.f('ix_audit_logs_created_at'), 'audit_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_audit_logs_entity_id'), 'audit_logs', ['entity_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_entity_name'), 'audit_logs', ['entity_name'], unique=False)
    op.create_index(op.f('ix_audit_logs_event_type'), 'audit_logs', ['event_type'], unique=False)
    op.create_index(op.f('ix_audit_logs_id'), 'audit_logs', ['id'], unique=False)
    op.create_index(op.f('ix_audit_logs_sha256_hash'), 'audit_logs', ['sha256_hash'], unique=False)
    op.create_table('campaigns',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=512), nullable=True),
    sa.Column('target_segment', sa.String(length=64), nullable=False),
    sa.Column('channel', sa.Enum('MULTI_CHANNEL', 'SMS', 'WHATSAPP', 'EMAIL', 'SMART_LINK', name='campaignchannel'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('total_targeted_count', sa.Integer(), nullable=False),
    sa.Column('total_recovered_count', sa.Integer(), nullable=False),
    sa.Column('total_revenue_recovered', sa.Float(), nullable=False),
    sa.Column('recovery_rate', sa.Float(), nullable=False),
    sa.Column('configuration', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_campaigns_active_created', 'campaigns', ['is_active', 'created_at'], unique=False)
    op.create_index(op.f('ix_campaigns_created_at'), 'campaigns', ['created_at'], unique=False)
    op.create_index(op.f('ix_campaigns_id'), 'campaigns', ['id'], unique=False)
    op.create_index(op.f('ix_campaigns_is_active'), 'campaigns', ['is_active'], unique=False)
    op.create_table('customers',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('rzp_customer_id', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=32), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('risk_score', sa.Float(), nullable=False),
    sa.Column('recovery_receptivity_score', sa.Float(), nullable=False),
    sa.Column('lifetime_recovered_amount', sa.Float(), nullable=False),
    sa.Column('extra_metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_customers_created_at'), 'customers', ['created_at'], unique=False)
    op.create_index(op.f('ix_customers_email'), 'customers', ['email'], unique=False)
    op.create_index(op.f('ix_customers_id'), 'customers', ['id'], unique=False)
    op.create_index(op.f('ix_customers_phone'), 'customers', ['phone'], unique=False)
    op.create_index(op.f('ix_customers_rzp_customer_id'), 'customers', ['rzp_customer_id'], unique=True)
    op.create_table('transactions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('customer_id', sa.String(length=36), nullable=False),
    sa.Column('rzp_order_id', sa.String(length=64), nullable=True),
    sa.Column('rzp_payment_id', sa.String(length=64), nullable=True),
    sa.Column('rzp_invoice_id', sa.String(length=64), nullable=True),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('status', sa.Enum('CREATED', 'AUTHORIZED', 'CAPTURED', 'FAILED', 'ABANDONED', 'RECOVERED', 'REFUNDED', name='transactionstatus'), nullable=False),
    sa.Column('payment_method', sa.Enum('CARD', 'UPI', 'NETBANKING', 'WALLET', 'EMI', 'SUBSCRIPTION', 'UNKNOWN', name='paymentmethod'), nullable=False),
    sa.Column('failure_code', sa.String(length=128), nullable=True),
    sa.Column('failure_reason', sa.String(length=512), nullable=True),
    sa.Column('failure_source', sa.String(length=64), nullable=True),
    sa.Column('error_step', sa.String(length=64), nullable=True),
    sa.Column('extra_metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transactions_created_at'), 'transactions', ['created_at'], unique=False)
    op.create_index(op.f('ix_transactions_customer_id'), 'transactions', ['customer_id'], unique=False)
    op.create_index(op.f('ix_transactions_failure_code'), 'transactions', ['failure_code'], unique=False)
    op.create_index(op.f('ix_transactions_id'), 'transactions', ['id'], unique=False)
    op.create_index(op.f('ix_transactions_rzp_invoice_id'), 'transactions', ['rzp_invoice_id'], unique=False)
    op.create_index(op.f('ix_transactions_rzp_order_id'), 'transactions', ['rzp_order_id'], unique=False)
    op.create_index(op.f('ix_transactions_rzp_payment_id'), 'transactions', ['rzp_payment_id'], unique=False)
    op.create_index(op.f('ix_transactions_status'), 'transactions', ['status'], unique=False)
    op.create_index('ix_transactions_status_created', 'transactions', ['status', 'created_at'], unique=False)
    op.create_table('payment_attempts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('transaction_id', sa.String(length=36), nullable=False),
    sa.Column('attempt_number', sa.Integer(), nullable=False),
    sa.Column('rzp_payment_id', sa.String(length=64), nullable=True),
    sa.Column('status', sa.Enum('INITIATED', 'SUCCESS', 'FAILED', 'CANCELLED', name='attemptstatus'), nullable=False),
    sa.Column('error_code', sa.String(length=128), nullable=True),
    sa.Column('error_description', sa.String(length=512), nullable=True),
    sa.Column('gateway_response', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_attempts_txn_attempt', 'payment_attempts', ['transaction_id', 'attempt_number'], unique=False)
    op.create_index(op.f('ix_payment_attempts_created_at'), 'payment_attempts', ['created_at'], unique=False)
    op.create_index(op.f('ix_payment_attempts_id'), 'payment_attempts', ['id'], unique=False)
    op.create_index(op.f('ix_payment_attempts_rzp_payment_id'), 'payment_attempts', ['rzp_payment_id'], unique=False)
    op.create_index(op.f('ix_payment_attempts_status'), 'payment_attempts', ['status'], unique=False)
    op.create_index(op.f('ix_payment_attempts_transaction_id'), 'payment_attempts', ['transaction_id'], unique=False)
    op.create_table('recovery_cases',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('transaction_id', sa.String(length=36), nullable=False),
    sa.Column('customer_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.Enum('OPEN', 'IN_PROGRESS', 'PENDING_APPROVAL', 'RECOVERED', 'ESCALATED', 'EXPIRED', 'UNRECOVERABLE', name='casestatus'), nullable=False),
    sa.Column('amount_at_risk', sa.Float(), nullable=False),
    sa.Column('recovered_amount', sa.Float(), nullable=False),
    sa.Column('recovery_score', sa.Integer(), nullable=False),
    sa.Column('risk_level', sa.String(length=32), nullable=False),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('max_retries_allowed', sa.Integer(), nullable=False),
    sa.Column('next_retry_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('strategy_summary', sa.String(length=512), nullable=True),
    sa.Column('requires_human_approval', sa.String(length=8), nullable=False),
    sa.Column('approval_reason', sa.String(length=255), nullable=True),
    sa.Column('extra_metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('recovered_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_cases_customer_status', 'recovery_cases', ['customer_id', 'status'], unique=False)
    op.create_index('ix_cases_status_created', 'recovery_cases', ['status', 'created_at'], unique=False)
    op.create_index(op.f('ix_recovery_cases_created_at'), 'recovery_cases', ['created_at'], unique=False)
    op.create_index(op.f('ix_recovery_cases_customer_id'), 'recovery_cases', ['customer_id'], unique=False)
    op.create_index(op.f('ix_recovery_cases_id'), 'recovery_cases', ['id'], unique=False)
    op.create_index(op.f('ix_recovery_cases_status'), 'recovery_cases', ['status'], unique=False)
    op.create_index(op.f('ix_recovery_cases_transaction_id'), 'recovery_cases', ['transaction_id'], unique=True)
    op.create_table('ai_decisions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('case_id', sa.String(length=36), nullable=False),
    sa.Column('failure_category', sa.String(length=64), nullable=False),
    sa.Column('root_cause_explanation', sa.String(length=1024), nullable=False),
    sa.Column('confidence_score', sa.Float(), nullable=False),
    sa.Column('recovery_probability', sa.Float(), nullable=False),
    sa.Column('reasoning_steps', sa.JSON(), nullable=False),
    sa.Column('risk_factors', sa.JSON(), nullable=False),
    sa.Column('recommended_action', sa.String(length=64), nullable=False),
    sa.Column('recommended_delay_minutes', sa.Integer(), nullable=False),
    sa.Column('recommended_channel', sa.String(length=32), nullable=False),
    sa.Column('model_name', sa.String(length=64), nullable=False),
    sa.Column('prompt_tokens', sa.Integer(), nullable=False),
    sa.Column('completion_tokens', sa.Integer(), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['recovery_cases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_decisions_case_id'), 'ai_decisions', ['case_id'], unique=False)
    op.create_index(op.f('ix_ai_decisions_created_at'), 'ai_decisions', ['created_at'], unique=False)
    op.create_index(op.f('ix_ai_decisions_failure_category'), 'ai_decisions', ['failure_category'], unique=False)
    op.create_index(op.f('ix_ai_decisions_id'), 'ai_decisions', ['id'], unique=False)
    op.create_index('ix_decisions_case_created', 'ai_decisions', ['case_id', 'created_at'], unique=False)
    op.create_table('recovery_actions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('case_id', sa.String(length=36), nullable=False),
    sa.Column('action_type', sa.Enum('DELAYED_RETRY', 'PAYMENT_LINK', 'SMART_NOTIFICATION', 'SWITCH_METHOD', 'HUMAN_ESCALATION', 'NO_ACTION', name='actiontype'), nullable=False),
    sa.Column('status', sa.Enum('PENDING_APPROVAL', 'SCHEDULED', 'EXECUTING', 'COMPLETED', 'FAILED', 'CANCELLED', 'REJECTED', name='actionstatus'), nullable=False),
    sa.Column('channel', sa.String(length=32), nullable=False),
    sa.Column('idempotency_key', sa.String(length=64), nullable=False),
    sa.Column('rzp_payment_link_id', sa.String(length=64), nullable=True),
    sa.Column('rzp_short_url', sa.String(length=255), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('result', sa.JSON(), nullable=True),
    sa.Column('policy_passed', sa.String(length=8), nullable=False),
    sa.Column('policy_rule_notes', sa.String(length=512), nullable=True),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('executed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['recovery_cases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_actions_case_status', 'recovery_actions', ['case_id', 'status'], unique=False)
    op.create_index(op.f('ix_recovery_actions_action_type'), 'recovery_actions', ['action_type'], unique=False)
    op.create_index(op.f('ix_recovery_actions_case_id'), 'recovery_actions', ['case_id'], unique=False)
    op.create_index(op.f('ix_recovery_actions_created_at'), 'recovery_actions', ['created_at'], unique=False)
    op.create_index(op.f('ix_recovery_actions_id'), 'recovery_actions', ['id'], unique=False)
    op.create_index(op.f('ix_recovery_actions_idempotency_key'), 'recovery_actions', ['idempotency_key'], unique=True)
    op.create_index(op.f('ix_recovery_actions_rzp_payment_link_id'), 'recovery_actions', ['rzp_payment_link_id'], unique=False)
    op.create_index(op.f('ix_recovery_actions_status'), 'recovery_actions', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_recovery_actions_status'), table_name='recovery_actions')
    op.drop_index(op.f('ix_recovery_actions_rzp_payment_link_id'), table_name='recovery_actions')
    op.drop_index(op.f('ix_recovery_actions_idempotency_key'), table_name='recovery_actions')
    op.drop_index(op.f('ix_recovery_actions_id'), table_name='recovery_actions')
    op.drop_index(op.f('ix_recovery_actions_created_at'), table_name='recovery_actions')
    op.drop_index(op.f('ix_recovery_actions_case_id'), table_name='recovery_actions')
    op.drop_index(op.f('ix_recovery_actions_action_type'), table_name='recovery_actions')
    op.drop_index('ix_actions_case_status', table_name='recovery_actions')
    op.drop_table('recovery_actions')
    op.drop_index('ix_decisions_case_created', table_name='ai_decisions')
    op.drop_index(op.f('ix_ai_decisions_id'), table_name='ai_decisions')
    op.drop_index(op.f('ix_ai_decisions_failure_category'), table_name='ai_decisions')
    op.drop_index(op.f('ix_ai_decisions_created_at'), table_name='ai_decisions')
    op.drop_index(op.f('ix_ai_decisions_case_id'), table_name='ai_decisions')
    op.drop_table('ai_decisions')
    op.drop_index(op.f('ix_recovery_cases_transaction_id'), table_name='recovery_cases')
    op.drop_index(op.f('ix_recovery_cases_status'), table_name='recovery_cases')
    op.drop_index(op.f('ix_recovery_cases_id'), table_name='recovery_cases')
    op.drop_index(op.f('ix_recovery_cases_customer_id'), table_name='recovery_cases')
    op.drop_index(op.f('ix_recovery_cases_created_at'), table_name='recovery_cases')
    op.drop_index('ix_cases_status_created', table_name='recovery_cases')
    op.drop_index('ix_cases_customer_status', table_name='recovery_cases')
    op.drop_table('recovery_cases')
    op.drop_index(op.f('ix_payment_attempts_transaction_id'), table_name='payment_attempts')
    op.drop_index(op.f('ix_payment_attempts_status'), table_name='payment_attempts')
    op.drop_index(op.f('ix_payment_attempts_rzp_payment_id'), table_name='payment_attempts')
    op.drop_index(op.f('ix_payment_attempts_id'), table_name='payment_attempts')
    op.drop_index(op.f('ix_payment_attempts_created_at'), table_name='payment_attempts')
    op.drop_index('ix_attempts_txn_attempt', table_name='payment_attempts')
    op.drop_table('payment_attempts')
    op.drop_index('ix_transactions_status_created', table_name='transactions')
    op.drop_index(op.f('ix_transactions_status'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_rzp_payment_id'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_rzp_order_id'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_rzp_invoice_id'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_id'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_failure_code'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_customer_id'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_created_at'), table_name='transactions')
    op.drop_table('transactions')
    op.drop_index(op.f('ix_customers_rzp_customer_id'), table_name='customers')
    op.drop_index(op.f('ix_customers_phone'), table_name='customers')
    op.drop_index(op.f('ix_customers_id'), table_name='customers')
    op.drop_index(op.f('ix_customers_email'), table_name='customers')
    op.drop_index(op.f('ix_customers_created_at'), table_name='customers')
    op.drop_table('customers')
    op.drop_index(op.f('ix_campaigns_is_active'), table_name='campaigns')
    op.drop_index(op.f('ix_campaigns_id'), table_name='campaigns')
    op.drop_index(op.f('ix_campaigns_created_at'), table_name='campaigns')
    op.drop_index('ix_campaigns_active_created', table_name='campaigns')
    op.drop_table('campaigns')
    op.drop_index(op.f('ix_audit_logs_sha256_hash'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_event_type'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_entity_name'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_entity_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_created_at'), table_name='audit_logs')
    op.drop_index('ix_audit_event_created', table_name='audit_logs')
    op.drop_index('ix_audit_entity_created', table_name='audit_logs')
    op.drop_table('audit_logs')
    # ### end Alembic commands ###
